project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    left:
      - text: "Αρχική"
        href: index.qmd
      - text: "Παρουσιάσεις"
        href: slides-index.qmd
      - text: "Σημειώσεις"
        href: notes-index.qmd
      - text: "Ασκήσεις"
        href: exercises-index.qmd

format:
  html:
    theme: default
    css: styles.css
    toc: true
    toc-title: Περιεχόμενα
